# Generated by Django 5.2.5 on 2025-08-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('password_hash', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
                ('token', models.CharField(max_length=100)),
            ],
        ),
    ]
